### ISSUE TITLE
Contest timings

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#103]
There is no concept of contest timings right now.

- Keep record of when the contest is supposed to start and end (maybe store datetime in the database / question set).
- make sure that APIs always follow the timings. For example, if time is up then the check api should no longer work.

**Comment by rishabhKalakoti** [comment]
Can you please elaborate this one? I got some doubts. Like... We will need  a moderator who decides the contest timings. Does a contest introduce new questions? Which are available for scoring during contest and later made public.
Mtlb I don't exactly understand how to get it started.

**Comment by theSage21** [comment]
Right now questions are picked up from the filesystem when the server starts. Thus the questions may be attempted as soon as the server starts.

This issue needs to implement some sort of time based system that can have **active/inactive** states.

For example, you might want to say that the contest runs from 12:00 Saturday to 14:00 Saturday. Then you can start receiving participants at 11:00 Saturday and have them go through the instructions / practice questions and at the appointed time the contest suddenly becomes visible.
