### ISSUE TITLE
404 handler

### ISSUE THREAD

**Issue by rishabhKalakoti** [PyJaipur/PyJudge#114]
Make a template and handler for requests with invalid urls and return that template whenever FileNotFound is invoked.

**Comment by rishabhKalakoti** [comment]
@theSage21 plz add `gfi` label to this one.

**Comment by theSage21** [comment]
you can refer to [this section of the bottle docs](https://bottlepy.org/docs/dev/tutorial.html#error-pages) to solve this issue
