### ISSUE TITLE
Proper question statement and support

### ISSUE THREAD

**Issue by rishabhKalakoti** [PyJaipur/PyJudge#115]
- [ ] Rewrite statements of problems 1 and 2
- [ ] Change problems 2-6 as they are a copies of problems 1 and 2
- [ ] Add more questions with test cases

**Comment by rishabhKalakoti** [comment]
This one should also a GFI I guess

**Comment by theSage21** [comment]
ah. good catch :+1: 

I had forgotten about this and thought this was about markdown based question statements with support reading material etc

**Comment by soumilk** [comment]
Can I replace these questions with the questions from other coding platforms ?

**Comment by theSage21** [comment]
maybe we should close this since it's no longer relevant. Let's focus on getting the question via web interface thing up and running first.

**Comment by rishabhKalakoti** [comment]
@theSage21 👍
