### ISSUE TITLE
User stats/ profile

### ISSUE THREAD

**Issue by rishabhKalakoti** [PyJaipur/PyJudge#127]
Statistics based on the submissions done by user.
Features:
* Submission History
* Accuracy (Correct Attempts/ Total submissions)
* Use calendar/ graph to show the frequency of submissions
Anything else that comes to mind, please add in comments

**Comment by Raul9595** [comment]
Can I work on this ?

**Comment by rishabhKalakoti** [comment]
Sure @Raul9595 go on.

**Comment by Megha-Pathak** [comment]
Can I help with this issue?

**Comment by rishabhKalakoti** [comment]
I think this one is already done in #131 You can take up another one :)
