### ISSUE TITLE
Move sample input file to the format suggested in #11

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#13]
The merge request for the question in #11 makes a folder and moves the question as a file in that folder. Let's keep the input file, output file, question statement in the same folder?

**Comment by theSage21** [comment]
For example, the following  standard structure could be used:

```
.
├── files
│   └── questions
│       ├── 1
│       │   ├── expected.txt
│       │   ├── inputs.txt
│       │   └── statement.html
│       ├── 2
│       │   ├── expected.txt
│       │   ├── inputs.txt
│       │   └── statement.html
│       └── 3
│           ├── expected.txt
│           ├── inputs.txt
│           └── statement.html
└── README.md
```

**Comment by theSage21** [comment]
Steps to solve
-----------------

Currently the folder structure looks like so:

```
.
├── css
│   └── styles.css
├── files
│   └── questions
│       └── inputs1.txt
├── index.html
├── README.md
└── server.py
```

Here the statement for question one is present in `index.html` and `server.py` files. Input data for the question is in `files/questions/inputs1.txt`

Let's put the statement HTML, input file, and output file (this is not yet present) for question 1 in the folder `files/questions/1/`. Let us call these files statement.html, inputs.txt, expected.txt

The server.py file will have to be edited to make it work with these changes.

**Comment by MPathak00** [comment]
I want to take this issue

**Comment by theSage21** [comment]
@MPathak00 do you need help?

**Comment by MPathak00** [comment]
Do I need to use file handling for the issue?

**Comment by theSage21** [comment]
You just have to copy par the files, rename properly and commit.

Then make changes in server.py
