### ISSUE TITLE
Serve the css file for the statement page

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#17]
The question statement page requires css files. Those files are not served by the server at the moment. We need to provide the css files just like we are providing the inputs for the questions. Maybe we can move both static files like css and input files to a single folder and serve that folder location?

**Comment by theSage21** [comment]
That sounds good

**Comment by jayeshchoubisa** [comment]
It should not send that file to server.py . it is instantiated only with that input page.

**Comment by theSage21** [comment]
I don't understand. could you be a little more clear?

**Comment by arnabsinha99** [comment]
I am not working on #17 . Anybody is free to take up this issue!

**Comment by jayeshchoubisa** [comment]
I am not able to contribute at the moment please someone take the initiative and follow along with the co members.

**Comment by HeroicHitesh** [comment]
Can I try this 1 out?

**Comment by theSage21** [comment]
Sure! Go ahead! The final thing will look something like [these lines](https://github.com/PyJaipur/PyJudge/blob/master/server.py#L33-L35)

**Comment by HeroicHitesh** [comment]
Sorry I was out of town but I looked at above lines of code and to me they don't seem to be CSS code.So i need to write CSS or python I don't understand.

**Comment by theSage21** [comment]
you will need to write python code. The CSS files are already written but not accessible (since nobody is serving them). To do that, just like we are serving question input files, we also need to write code to serve static files (which include CSS).

**Comment by HeroicHitesh** [comment]
Then I don't think I will be able to solve this as I thought this was a css problem.For python I need help.Can you explain the lines of code you have given?

**Comment by theSage21** [comment]
Apparently this issue is very difficult to solve. Can someone please ask questions regarding the difficulty they are facing? I can help but unless you tell me what you are thinking I cannot.

For example #80 simply makes code changes in a completely different file. @HeroicHitesh why do you expect that code to work? The change needs to be made in the `server.py` file.

[ You need to serve static files from the server](https://bottlepy.org/docs/0.12/tutorial.html#routing-static-files)... please ask questions if something is not clear.

**Comment by HeroicHitesh** [comment]
> 
> 
> Apparently this issue is very difficult to solve. Can someone please ask questions regarding the difficulty they are facing? I can help but unless you tell me what you are thinking I cannot.
> 
> For example #80 simply makes code changes in a completely different file. @HeroicHitesh why do you expect that code to work? The change needs to be made in the `server.py` file.
> 
> [ You need to serve static files from the server](https://bottlepy.org/docs/0.12/tutorial.html#routing-static-files)... please ask questions if something is not clear.

I thought I need to write code and then after merge request it will be added to the server.py file

**Comment by theSage21** [comment]
Write the final thing no. No point in us reviewing things twice
