### ISSUE TITLE
Add link for PyJudge telegram group in README

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#18]
A link needs to be added to the README which points to the PyJudge telegram group

**Comment by arnabsinha99** [comment]
I am on it. Where exactly do I need to add it?

**Comment by arnabsinha99** [comment]
> 
> 
> A link needs to be added to the README which points to the PyJudge telegram group

Could I have the link for the Pyjudge telegram group?

**Comment by theSage21** [comment]
You can put it right next to the PyJaipur link.

**Comment by arnabsinha99** [comment]
> 
> 
> You can put it right next to the PyJaipur link.

Kindly review the changes.
