### ISSUE TITLE
Showing the submission page

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#2]
The web server must show a HTML page which has the following:

- place to show a question statement
- link to download the test input data
- a form to upload their output file

How to solve
----------------

- Fork this project. You can see a Fork button on the top right of this project page.
- Use the [Bottle](https://bottlepy.org) framework to do this since it's very simple to use. Put your code in a file called `server.py`
- Commit your changes and submit a pull request to this project.

**Comment by theSage21** [comment]
Awesome!

**Comment by rustagishubhi** [comment]
Can I add bootstrap files along with HTML file so as to add the CSS to the page?

**Comment by theSage21** [comment]
this is the first phase. Let's keep it simple for now. Vanilla CSS is ok but a full heavyweight framework like bootstrap will take away the opportunity to learn things.

**Comment by theSage21** [comment]
@rustagishubhi are you working in collaboration with @Shivank98 ? If you have some code do submit it for review please
