### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#20]
Since people are opening pull requests now, it's becoming irritating to manually close issues which the PR solves. A Pull request template will solve this.

Refer to [github docs on PR templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) and add a template. The template should ask the person to mention the issue that they are trying to solve. Then when the PR is merged, the issue is closed automatically.

**Comment by soumilk** [comment]
I want to take this issue

**Comment by anjalijain1998** [comment]
I also want to work on this issue

**Comment by theSage21** [comment]
maybe one of you could a pull request template and another one could do an issue template?

**Comment by anjalijain1998** [comment]
sure i am going for pull request template

**Comment by soumilk** [comment]
@theSage21  please clarify Issue template? How this template is supposed to !

**Comment by theSage21** [comment]
You can have a simple issue template like so:

1. Please define your issue clearly
2. Add a label if it is appropriate

**Comment by soumilk** [comment]
ohk ... got it

**Comment by theSage21** [comment]
@anjalijain1998 we will keep the issue open until you submit a PULL_REQUEST template code change. Please make sure to remind people to refer to issue in the PR so that they will be auto closed. [reference](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)

**Comment by anjalijain1998** [comment]
@theSage21 sir I have made this file but now what I have to do ? 
please check it and let me know if I have done it correct or not!!

[PULL_REQUEST_TEMPLATE.md.txt](https://github.com/PyJaipur/PyJudge/files/2768937/PULL_REQUEST_TEMPLATE.md.txt)

**Comment by theSage21** [comment]
Please don't call me sir. Arjoonn or @theSage21 is fine.

The file looks wonderful :+1: 

Open up a Merge request

**Comment by anjalijain1998** [comment]
ohk sure
