### ISSUE TITLE
Avoid file write in user output checking

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#25]
In [the file upload code](https://github.com/PyJaipur/PyJudge/blob/master/server.py#L35-L51), the uploaded file is written to filesystem. We can avoid that by simply accessing the string directly using `request.files.get('upload').file.read()` and comparing that to the expected output.

The expected file is read every time the URL is called. We can read the file once and store the expected string globally and simply use that in the API. Thus the api will have no File read write inside it. Only string comparison.

How to Solve
----------------

- [According to bottle docs](https://bottlepy.org/docs/dev/api.html#bottle.FileUpload) the FileUpload object has an open file object. Simply read that and obtain a string.
- Move the expected file reading code outside the URL function code. Maybe somewhere just after the `app = Bottle()` code. Store the expected string in a variable.
- In the API, simply read the user string and compare to expected string.

**Comment by arnabsinha99** [comment]
I'll have a try at this one since this is an extension to my previous submission.

**Comment by theSage21** [comment]
Awesome
