### ISSUE TITLE
Record history of all user's attempts

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#28]
As users attempt questions, we need to record their attempts somehow. For now, we must store the attempts in a list. The information to store can be `username, correct_or_not, question_number`

**Comment by Shivank98** [comment]
I would like to work on it. will work on it from the night.

**Comment by Shivank98** [comment]
but I will require #26. so I can have an intuition of where username is being stored.

**Comment by theSage21** [comment]
since nobody is working on that right now, you can do something like:

```python
user_attempt_history = []  # TODO: This needs to be filled out
```

Then whoever works on that issue can use the same thing

**Comment by Shivank98** [comment]
last time i worked on something like this which require user atempts or records of action. i needed forms. 
do i require it here too ?

**Comment by theSage21** [comment]
There's already a form in the submission page. Just add a field there no?

**Comment by Shivank98** [comment]
test

**Comment by HeroicHitesh** [comment]
@Shivank98 Ab kar skta hoon

**Comment by Shivank98** [comment]
tell me if I got it right?
do we have to count the `number_of_attempts` in a period when a server is running for a particular question? 
like the number of times user uploaded the output file.

**Comment by theSage21** [comment]
For now it's ok to just add `(name, question_number, correct_or_not, time)` to a list every time someone makes an attempt

**Comment by Shivank98** [comment]
got it.
