### ISSUE TITLE
Multiple questions ability

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#29]
The system must be able to show multiple questions. Thus the HTML must have a variable part which has the question in it. Refer to Bottle's documentation on the template system. We will be using that.

During attempts also, there must be a field which mentions which question the person is attempting so that the given output can be checked against the correct "expected.txt" file.

**Comment by Shivank98** [comment]
let me know where i am wrong.
* i am going to make a `question_template.tpl` which will solve this issue. but 
* with this i will need below structure.
```
├── files
│   └── questions
│       ├── 1
│       │   ├── expected.txt
│       │   ├── inputs.txt
│       │   └── statement.txt   # this will basically have the question in text format.
│       ├── 2
│       │   ├── expected.txt
│       │   ├── inputs.txt
│       │   └── statement.txt
```

are these two steps correct ?

**Comment by theSage21** [comment]
both points look good. The `question.tpl` file contains space to show the information present in `statement.txt`?

**Comment by theSage21** [comment]
You will also need to modify `server.py` to:

- properly read expected output
- properly check uploaded output
- properly provide input and question statement
