### ISSUE TITLE
Providing the input file for download

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#3]
A participant must be able to download an input file related to the question. She will then run her program on this input file and produce an output file according to the question's instructions.

The web server must be able to supply this file when the participant asks for it by clicking on the link mentioned in #2 

How to solve
----------------

- Fork this project. You can see a Fork button on the top right of this project page.
- Use the [Bottle](https://bottlepy.org) framework to do this since it's very simple to use. Put your code in a file called `server.py`
- Commit your changes and submit a pull request to this project.

**Comment by yashj13** [comment]
@theSage21,i want to take this issue, can i start working on it?

**Comment by theSage21** [comment]
Sure sure!

**Comment by theSage21** [comment]
@yashj13 I think this was solved in #11 in the `/question/<number>/download` url. You can close the issue if you agree.
