### ISSUE TITLE
Ranking / Leaderboard

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#30]
A new URL must be written along with corresponding HTML page to display the user's ranking. The ranking must be calculated on some scoring system (for example how many questions have you correctly attempted?).

this ranking must display the user's names and their rank.

**Comment by piyushagarwal08** [comment]
I want to try this issue.. but as a beginner can I get guidance (step by step)? Something by which I would know what I am supposed to do.(note:never worked over such an project previously)

**Comment by theSage21** [comment]
What is the difference between the two kinds of lists?

**Comment by arnabsinha99** [comment]
[Here](https://www.codechef.com/rankings) is the site that proposed what I am talking about. The different kind of ranking lists.

**Comment by theSage21** [comment]
Sure! How do you plan to make the different rankings available to the HTML? Separate URLs? Maybe something like:

`/rankings/<style>/` can be used

**Comment by arnabsinha99** [comment]
Yeah. I mean we can make the templates and use it based on what the host decides, to make it score based or rank based. We can accept a parameter from the host of the contest which chooses between the different types of rank-lists. And as per her/his choice, we can deploy the required HTML page URL. @theSage21

**Comment by theSage21** [comment]
Let's maintain a single ranking system in this issue. For the multiple rankings we can solve that in another issues.

**Comment by arnabsinha99** [comment]
The `%` syntax to include Python code does not seem to work in the `Rankings.html` file. It simply is printing the exact lines of code. What could be the possible reason? @theSage21

**Comment by theSage21** [comment]
That only works if you use the template function. Could you open a pr so that I can look at code. Otherwise it's very difficult to guess what could be going wrong
