### ISSUE TITLE
Remove testing code

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#35]
The code present in [these lines](https://github.com/PyJaipur/PyJudge/blob/master/server.py#L12-L14) is not relevant to the software we are trying to build. It needs to be removed.

**Comment by theSage21** [comment]
The [commented out code](https://github.com/PyJaipur/PyJudge/blob/master/server.py#L20-L26) can also be removed.

**Comment by HeroicHitesh** [comment]
I want to solve this issue

**Comment by HeroicHitesh** [comment]
I think in this issue we just need remove the unwanted lines of code and comments and post the remaining code as it is.
If I am wrong then please do correct me.
