### ISSUE TITLE
reading a file when required. discussion needed.

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/PyJudge#39]
* **I am submitting this regarding **
	
	- [ ] Bug report 
	- [ ] Feature request 
	- [ ] Support request
	- [ ] Help request 
	- [x] Discussion or tutorial wanted 

* **Description of the ISSUE:** 
currently, the file is read everytime server is run.
I want the file to be read only when it's required and someone is uploading his file to be checked.

**Comment by theSage21** [comment]
Typically, the server is run once and then it keeps on running. It is only restarted if something goes wrong or if code needs to be updated in the server.

**Comment by theSage21** [comment]
Yes. In future we will need multiple expected outputs. Maybe at that time
we will simply read all of them before hand and put them in a dictionary
where's the key is the question number and use that.

Or you could have a database and let that software manage when to read and
when to keep in memory.

We will be doing that in a later project. In this project we will only be
introducing multi use and multi question system.

**Comment by Shivank98** [comment]
Ohk, That's a lot of space :D
* 1. another thing which I just faced is this, don't know how it got missed.
`
expected = expected.strip()
UnboundLocalError: local variable 'expected' referenced before assignment
` 
while running server.py. 
so we will need to add a `global expected` in `url_upload`.

* 2. it's giving 'Wrong answer' even I am submitting the right answer.
looks like we are going to need more issues.

**Comment by theSage21** [comment]
Please feel free to open them

**Comment by Shivank98** [comment]
I will positively do it in night. and i will add global expected myself.
