### ISSUE TITLE
Accepting a participant's output file

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#4]
We need a place for the participant to upload her program's output. We should be able to accept a plain text file from the form mentioned in #2 

On accepting the file, we have to compare it to a known output file and tell the user if the output was correct or not.

How to solve
----------------

- Fork this project. You can see a Fork button on the top right of this project page.
- Use the [Bottle](https://bottlepy.org) framework to do this since it's very simple to use. Put your code in a file called `server.py`
- The expected output file can be saved separately with the name `expected_output.txt`
- Commit your changes and submit a pull request to this project.

**Comment by arnabsinha99** [comment]
I am up for #4

**Comment by theSage21** [comment]
Wonderful!

**Comment by arnabsinha99** [comment]
Is there any other source, Just for additional reference , to refer for Bottle framework other than the documentation? @theSage21

**Comment by theSage21** [comment]
@arnabsinha99 any updates?

**Comment by arnabsinha99** [comment]
I have started to understand what Bottle is and some syntaxes.. I will soon do it as I need some more time.

**Comment by theSage21** [comment]
Wonderful!

**Comment by jayeshchoubisa** [comment]
@arnabsinha99 has you done with the issue. I am also trying to merge the code but having some issues.

**Comment by theSage21** [comment]
Merge? Is there a pull request?

Also if you are having problems ask here

**Comment by arnabsinha99** [comment]
> 
> 
> @arnabsinha99 has you done with the issue. I am also trying to merge the code but having some issues.

Have you continued with the same code after the "server.py" file that is already made or have you made a new "server.py" file ?

**Comment by arnabsinha99** [comment]
@theSage21 In the "Browse files" button, the user has to submit only the produced output that he/she has got right? Do we have to accept the code as well?

**Comment by theSage21** [comment]
no. only the output file that they have produced

**Comment by arnabsinha99** [comment]
Where do I store the file that we are accepting?

**Comment by jayeshchoubisa** [comment]
I am confused with one thing are we using any platform to run the code and check the correctness.

**Comment by theSage21** [comment]
no need to store it. Just like we have the question's input file, we need one expected output file also. The file that the user uploaded we just have to read that, compare to the expected file and return if thy are equal or not.

Maybe something like:

```python
def fn():
    uploaded = somehow_get_the_uploaded_file_text()
    with open('expected_file_path', 'r') as fl:
        expected = fl.read()
    return 'Solved!' if expected == uploaded else 'wrong answer'
```

**Comment by theSage21** [comment]
In this project we are not running code. We are simply checking if output supplied matches expected output. In later sprints we will be running code also (Java / C) etc.

**Comment by theSage21** [comment]
By project I mean https://github.com/PyJaipur/PyJudge/projects

**Comment by jayeshchoubisa** [comment]
yeah okay

**Comment by jayeshchoubisa** [comment]
has you got executed with it.

**Comment by theSage21** [comment]
मतलब?

**Comment by jayeshchoubisa** [comment]
has you got executed with this commit.

**Comment by jayeshchoubisa** [comment]
has you got executed with it.

**Comment by jayeshchoubisa** [comment]
tumne issue resolve kar diya with function for submit

**Comment by arnabsinha99** [comment]
I am on it. It is completely new and I am getting the hang of it slowly.

**Comment by jayeshchoubisa** [comment]
same here .

**Comment by theSage21** [comment]
Lage raho. Koi sawaal ho toh yahan puch lena.

**Comment by theSage21** [comment]
Are you tying to push to this repository?

You have to fork this, push to your repo and then open a merge request.

There are a lot of tutorials on the internet regarding this.

https://github.com/PyJaipur/PyJaipur-first-PR

**Comment by arnabsinha99** [comment]
I had forked the original repo by mistake even though I was aware of the steps. I apologize for the inconvenience.  I have made a pull request recently. Kindly review it. Thanks @theSage21

**Comment by theSage21** [comment]
no problem. :+1:

**Comment by theSage21** [comment]
#24 fixed this
