### ISSUE TITLE
Add tests for the code

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#43]
As found out in [another discussion](https://github.com/PyJaipur/PyJudge/issues/39#issuecomment-455771059) the project is now big enough that simply reading the code during review does not ensure that it will run.

For starters a simple test file is needed which can run the server and make sure it does not crash. Later on we can add more tests.

**Comment by Shivank98** [comment]
do we still need it?
i can work on it.

**Comment by Shivank98** [comment]
ok then, I am on it.  do I need to keep something in mind for the approach ? as i don't have any experience with travis or circle, just little bit of unit tests.

**Comment by theSage21** [comment]
For now I think simply testing if the server runs is enough. Later on as need increases we can improve testing standards.

**Comment by theSage21** [comment]
that will catch all syntax errors and so on.

**Comment by Shivank98** [comment]
while writing the tests i faced a error, i tried google too but didn't understand it. else it test for other two functions in `server.py` are running `OK`. 
```
def test_file_upload(self):
        #assert app.post('/check/1').status_code == 200
        print(app.post('/check/1').status_code)
```

and this give me this error.
```
ERROR: test_file_upload (test_pyjudge.TestPyJudge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shivank98/Desktop/PyJudge/PyJudge/test_pyjudge.py", line 16, in test_file_upload
    print(app.post('/check/1').status_code)
  File "/home/shivank98/anaconda3/lib/python3.7/site-packages/webtest/app.py", line 382, in post
    content_type=content_type)
  File "/home/shivank98/anaconda3/lib/python3.7/site-packages/webtest/app.py", line 758, in _gen_request
    expect_errors=expect_errors)
  File "/home/shivank98/anaconda3/lib/python3.7/site-packages/webtest/app.py", line 654, in do_request
    self._check_status(status, res)
  File "/home/shivank98/anaconda3/lib/python3.7/site-packages/webtest/app.py", line 686, in _check_status
    res)
webtest.app.AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/check/1)

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:80/check/1&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>
```

**Comment by theSage21** [comment]
can we please stop having code in comments. Just submit a PR and we can discuss things there.

**Comment by Shivank98** [comment]
sure sure, my bad

**Comment by Shivank98** [comment]
@theSage21 i am back. is this issue still on ?
or if i can remember you added tests yourself?

**Comment by theSage21** [comment]
This is still on. I haven't written any code I can remember for this

**Comment by cquark7** [comment]
Hey @theSage21, I think it would be better to use `pytest` as our testing framework. What do you think?

**Comment by theSage21** [comment]
#68 is already doing that I think
