### ISSUE TITLE
A sample question must be written along with sample input and expected output files

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#5]
We need a sample question. The question statement must be included either in the HTML in #2 or in another file (maybe named `statement.txt`) and combined with the template feature in the Bottle framework.

A nice question I like is "Given a file which has numbers on every line, generate a file which has the squares of those numbers on corresponding lines"

How to solve
----------------

- Fork this project. You can see a Fork button on the top right of this project page.
- Use the [Bottle](https://bottlepy.org) framework to do this since it's very simple to use. Put your code in a file called `server.py`
- Commit your changes and submit a pull request to this project.

**Comment by Shivank98** [comment]
@theSage21 I would like to take this.

**Comment by theSage21** [comment]
Please go ahead.
