### ISSUE TITLE
Use template inheritance to reuse code between ranking and question html

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#62]
The question and ranking HTML both define some common things (like HTML, HEAD, BODY).
We can move the common things into a `base.html` file and use that in both `question.html` and `rankings.html`. See [bottle template functions](https://bottlepy.org/docs/dev/stpl.html#template-functions) to understand how to do this.

Final folder structure can look like:

```
.
├── css
│   └── styles.css
├── files
│   └── questions
│       ├── 1
│       │   ├── inputs.txt
│       │   ├── output.txt
│       │   └── statement.txt
│       └── 2
│           ├── inputs.txt
│           ├── output.txt
│           └── statement.txt
├── README.md
├── server.py
└── templates
    ├── base.html
    ├── question.html
    └── ranking.html
```

**Comment by arnabsinha99** [comment]
What is `base.html' used for ?

**Comment by theSage21** [comment]
Generally it is used to do common things like set the font for the whole
site. If you use things like bootstrap and jquery then those links are put
in the base.

Common navigation bars and footers are put in the base.

**Comment by arnabsinha99** [comment]
Has it been worked on? I don't seem to find it. @theSage21

**Comment by theSage21** [comment]
Oh no no. You will have to create it

**Comment by HeroicHitesh** [comment]
I am taking this issue
