### ISSUE TITLE
Update readme with details on how to run software on your local.

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/PyJudge#65]
I found this one missing from our README.md. and I think it is very important to have if anyone new would like to contribute. so it would be great if we can update readme for that.

**Comment by soumilk** [comment]
When I run the server.py, it is showing me this,
![screenshot from 2019-01-28 10-21-22](https://user-images.githubusercontent.com/31521503/51815515-66437f00-22e7-11e9-8794-2191017dbf61.png)


Now what to do after this ? I mean how can I see project working

**Comment by Shivank98** [comment]
go to https://localhost:8080/questions/1

**Comment by soumilk** [comment]
Showing an error 404.

![screenshot from 2019-01-28 11-20-43](https://user-images.githubusercontent.com/31521503/51817029-2bdde000-22ef-11e9-9f7f-7d0de4931f28.png)

In terminal 
127.0.0.1 - - [28/Jan/2019 11:20:34] "GET /questions/1 HTTP/1.1" 404 742

**Comment by Shivank98** [comment]
*question
and it would be appropriate if you ask this question in #71. 
this issue Serve other purpose.

**Comment by soumilk** [comment]
Ok
