### ISSUE TITLE
problem with line 20 in server.py while running the server using python server.py

### ISSUE THREAD

**Issue by gauravrock** [PyJaipur/PyJudge#71]
## some problem on line 20 server.py while running the server using python server.py(it happens sometimes)

![screenshot 2019-01-27 at 12 31 36 am](https://user-images.githubusercontent.com/23530368/51804887-28653d00-228c-11e9-8b8a-3cfdabdd1f57.png)

**Comment by Shivank98** [comment]
can you share your folder structure ?

**Comment by Shivank98** [comment]
i think it's case of mac. and we need to add `DS_Store` in `.gitignore`.

**Comment by gauravrock** [comment]
I' ll try to do it @Shivank98. it happens sometimes once it runs but somehow whenever it gets 404 error the next time it gives this error.

**Comment by Shivank98** [comment]
yeah try deleting that Ds.. folder for check.

**Comment by arnabsinha99** [comment]
I am still getting the 404 Not found error. Could anyone whose `server.py` is running, help?

**Comment by gauravrock** [comment]
> I am still getting the 404 Not found error. Could anyone whose `server.py` is running, help?

share the screenshot @arnabsinha99  please

**Comment by arnabsinha99** [comment]
> 
> 
> > I am still getting the 404 Not found error. Could anyone whose `server.py` is running, help?
> 
> share the screenshot @arnabsinha99 please

![screenshot 78](https://user-images.githubusercontent.com/29712938/51849733-5444f900-2346-11e9-9fe9-74588fea66e0.png)
![screenshot 79](https://user-images.githubusercontent.com/29712938/51849736-5444f900-2346-11e9-91f0-884b82829e82.png)

**Comment by gauravrock** [comment]
@arnabsinha99  your server is running. Please enter this URL after running the server.py: http://localhost:8080/question/1

**Comment by arnabsinha99** [comment]
alright. that worked thanks!. some more issues I faced are :- 

* The "download test cases" is not giving me the test case file

* It is giving the wrong answer for "sum of two numbers" even though my output file is correct.
