### ISSUE TITLE
only static html file no css 

### ISSUE THREAD

**Issue by gauravrock** [PyJaipur/PyJudge#76]
## ISSUE Template 

- [x] This is a
	- Help request 
	- Discussion or tutorial wanted 
- my issue is why running the command python server.py and then http://localhost:8080/question/1 only shows the static HTML page & not CSS because yesterday it was working fine by doing the same.
- however, I am able to see all the embed CSS in HTML file:///Users/apple/Desktop/project/PyJudge/index.html. but the thing that is not running the project.
#74

**Comment by rishabhKalakoti** [comment]
I think it works fine now and should be closed.

**Comment by gauravrock** [comment]
@theSage21 please close this issue!! it works for now

**Comment by rishabhKalakoti** [comment]
@gauravrock you can close the issue yourself as you are the author.
