### ISSUE TITLE
Issue to fix #17

### ISSUE THREAD

**Issue by HeroicHitesh** [PyJaipur/PyJudge#79]
## ISSUE Template 

- [ ] This is 
	- Feature request 
I am trying  to show code to serve css file
- [ ] Description
- [ ] I have applied the appropriate labels for this issue
- [ ] I have provided steps to reproduce the bug (If a bug report)

**Comment by HeroicHitesh** [comment]
How to delete this issue which I opened mistakenly.

**Comment by cquark7** [comment]
@HeroicHitesh You can't delete issues on Github (afaik, only project admins can do that).
https://stackoverflow.com/questions/3081521/how-to-completely-remove-an-issue-from-github

**Comment by HeroicHitesh** [comment]
> 
> 
> @HeroicHitesh You can't delete issues on Github (afaik, only project admins can do that).
> [Github - remove issues entered in error](https://stackoverflow.com/questions/3081521/how-to-completely-remove-an-issue-from-github)

Not even I opened the issue?
