### ISSUE TITLE
Fix missing return statement in server file.

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#91]
I think the missing return statement was missed during review. Someone please add it on [this line](https://github.com/PyJaipur/PyJudge/blob/master/server.py#L30)

**Comment by arnabsinha99** [comment]
> I think the missing return statement was missed during review. Someone please add it on [this line](https://github.com/PyJaipur/PyJudge/blob/master/server.py#L30)

What should be returned?

**Comment by theSage21** [comment]
the redirect function call? I think it works without that also but for the sake of cleanliness I'd like it returned

**Comment by rishabhKalakoti** [comment]
Time to close this one :)
