### ISSUE TITLE
Integrate black into our project

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#93]
Our project now has some logic code (like the ranking function). Since these functions/computations can be written over multiple lines, code formatting becomes an issue. Different people have different styles of writing the same code.

To make collaboration easier, we don't leave it up to the programmer to select a style. We enforce a style using [Black](https://github.com/ambv/black).

To solve this issue, go through the README of the Black project and set it up with the git pre commit hook method as mentioned [in this part of the README](https://github.com/ambv/black#version-control-integration)

**Comment by rishabhKalakoti** [comment]
#94 : integrated black.
