### ISSUE TITLE
Move rankings html to template folder

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/PyJudge#96]
The `Rankings.html` file is supposed to be in the `templates` folder and the server has to use it from there.

related to #62

**Comment by rishabhKalakoti** [comment]
Then, I think we will need to move `index.html` to the `templates` folder too as it is also a part of the template.

**Comment by theSage21** [comment]
yes. basically you'll need a template system overhaul

**Comment by rishabhKalakoti** [comment]
made a PR: #99 to handle the issue.

**Comment by theSage21** [comment]
instead of commenting here, in your PR description do something like `fixes #96`

**Comment by theSage21** [comment]
that way the issue gets automatically linked to the PR
